export const US_STATES = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
];

export const US_HOSPITALS = [
    { value: 'HCA Healthcare', label: 'HCA Healthcare' },
    { value: 'Mayo Clinic', label: 'Mayo Clinic' },
    { value: 'Cleveland Clinic', label: 'Cleveland Clinic' },
    { value: 'Kaiser Permanente', label: 'Kaiser Permanente' },
    { value: 'Ascension', label: 'Ascension' },
    { value: 'Tenet Healthcare', label: 'Tenet Healthcare' },
    { value: 'CommonSpirit Health', label: 'CommonSpirit Health' },
    { value: 'Providence', label: 'Providence' },
    { value: 'Trinity Health', label: 'Trinity Health' },
    { value: 'UHS (Universal Health Services)', label: 'UHS (Universal Health Services)' },
    { value: 'Johns Hopkins Medicine', label: 'Johns Hopkins Medicine' },
    { value: 'Mass General Brigham', label: 'Mass General Brigham' },
    { value: 'UPMC (University of Pittsburgh Medical Center)', label: 'UPMC (University of Pittsburgh Medical Center)' },
    { value: 'Mount Sinai Health System', label: 'Mount Sinai Health System' },
    { value: 'NYU Langone Health', label: 'NYU Langone Health' },
    { value: 'Intermountain Healthcare', label: 'Intermountain Healthcare' },
    { value: 'Atrium Health', label: 'Atrium Health' },
    { value: 'Sutter Health', label: 'Sutter Health' },
    { value: 'Advocate Health Care', label: 'Advocate Health Care' },
    { value: 'Baylor Scott & White Health', label: 'Baylor Scott & White Health' },
    { value: 'Banner Health', label: 'Banner Health' },
    { value: 'Northwell Health', label: 'Northwell Health' },
    { value: 'Other/Custom Facility', label: 'Other/Custom Facility' }
];
